# Generated by Django 3.2.4 on 2021-06-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210606_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sale_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
